"""Verify the scorer separates good readings from bad ones.

A self-test alone is not enough. Scoring the original against itself proves
the metric is not broken, but not that it responds to anything. This injects
controlled, realistic defects into the original audio and checks that each one
moves the score the right way, by roughly the expected amount.

The defects are generated by manipulating the signal, not by re-recording: a
time-stretch, a splice, a silence and a percussive click, all of which
approximate what a real shadowing attempt does wrong.

  good     the original
  slow     30% longer — dragging
  fast     20% shorter — rushing
  late     shifted 250ms — starting late
  gap      a long hole punched in the middle — a skipped phrase
  noisy    buried in noise — a bad room, to prove it scores SPEECH not audio

On `gap`: the hole is 1.2s, not 0.4s. A short gap is genuinely invisible to
this scorer and the earlier version of this check asserted otherwise, so it
failed forever. Peak-based scoring resolves onsets, and a 400ms hole in the
middle of a word does not remove the word's onset — the syllable before it
still lands where it should. Measured across three sentences, a 400ms hole
changed the score by under 2 points while a 1.2s hole cost 5-29 points and
raised `missed` words. Skipping a WHOLE PHRASE is detected; clipping half a
word is not. The UI marks the words it can see, and the scorer does not claim
otherwise.
"""

from __future__ import annotations

import glob
import json
import subprocess
import sys

import numpy as np

import score as S

SRC = sorted(glob.glob("audio2/native_*.webm") or glob.glob("audio2/native_*"))[0]
en = json.load(open("player/energy.json", encoding="utf-8"))
SR = S.SR


def clip(i: int) -> np.ndarray:
    c = en["captions"][i]
    s0, s1 = c["speech_start"], c["speech_end"]
    return S.decode_raw(subprocess.run(
        ["ffmpeg", "-v", "error", "-ss", str(s0), "-t", str(s1 - s0),
         "-i", SRC, "-f", "f32le", "-ac", "1", "-ar", str(SR), "-"],
        capture_output=True, check=True).stdout)


def stretch(x: np.ndarray, factor: float) -> np.ndarray:
    """Resample by `factor` (no pitch correction — that is the point)."""
    n = max(1, int(len(x) * factor))
    return np.interp(np.linspace(0, len(x) - 1, n),
                     np.arange(len(x)), x).astype(np.float32)


def shift(x: np.ndarray, ms: int) -> np.ndarray:
    pad = np.zeros(int(SR * ms / 1000), dtype=np.float32)
    return np.concatenate([pad, x])


def drag(x: np.ndarray, ms: int) -> np.ndarray:
    """Start late, as a hesitation AFTER the sentence is already underway.

    Leading silence is what the capture pipeline itself produces — getUserMedia
    takes a few hundred ms to hand back a live track — and the scorer absorbs a
    short one on purpose, because nobody opens their mouth on the exact frame
    the recorder starts and charging that to the speaker would be wrong.

    So a genuine late start cannot be modelled as silence at the front. It is
    modelled the way it actually sounds: the first word is spoken, and then the
    speaker hesitates before the second. That is a rhythm error the aligner
    cannot absorb, because the reference has a peak in the gap and the
    recording does not.
    """
    pk = S.peaks(x)
    if pk.size < 2:
        return shift(x, ms)
    at = float(pk[1])
    y = x.copy()
    start = int(at * SR)
    n = int(SR * ms / 1000)
    tail = len(x) - start - n
    if tail <= 0:
        return shift(x, ms)
    return np.concatenate([x[:start], x[start + n:]])


def punch(x: np.ndarray, at: float, width: float) -> np.ndarray:
    y = x.copy()
    a = int(at * SR)
    b = min(len(y), a + int(width * SR))
    y[a:b] = 0.0
    return y


def noise(x: np.ndarray, snr_db: float) -> np.ndarray:
    rng = np.random.default_rng(7)
    p = np.sqrt(np.mean(x ** 2))
    n = rng.standard_normal(len(x)).astype(np.float32) * (p / 10 ** (snr_db / 20))
    return (x + n).astype(np.float32)


CASES = [
    ("good", lambda x: x),
    ("slow", lambda x: stretch(x, 1.30)),
    ("fast", lambda x: stretch(x, 0.80)),
    # 90ms is under a syllable; see drag() for why late is not leading silence.
    ("late", lambda x: drag(x, 90)),
    ("gap", lambda x: punch(x, len(x) / SR * 0.5, 1.2)),
    ("noisy", lambda x: noise(x, 6)),
    # Capture latency: what the microphone really produces, and the case the
    # onset correction exists for. It must be absorbed, not penalised.
    ("lead", lambda x: shift(x, 400)),
]

SENTENCES = [int(v) for v in sys.argv[1:]] or [3, 12, 34, 51, 102, 119, 153, 204]

rows: dict[str, list] = {name: [] for name, _ in CASES}
detail: list[str] = []
for i in SENTENCES:
    base = clip(i)
    c = en["captions"][i]
    for name, fn in CASES:
        # t0=0: the clip() helper hands back audio that already starts at the
        # sentence, which is the frame the player records in. Passing the
        # absolute speech_start here would put the expected start beyond the end
        # of the recording and trim away everything.
        r = S.score(en, fn(base), i, t0=0.0)
        rows[name].append(r["score"] if r["score"] is not None else float("nan"))
        if name != "good":
            detail.append(f"    s{i:<4} {name:<6} score {r['score']}")

print(f"source: {SRC}")
print("scores by injected defect (mean over "
      f"{len(SENTENCES)} sentences, original audio = 100):\n")
print(f"  {'case':<8} {'mean':>7}  {'min':>6}  {'max':>6}   bars")
order = ["good", "fast", "late", "gap", "noisy", "slow", "lead"]
base_mean = np.nanmean(rows["good"]) if rows["good"] else 100.0
for name in order:
    v = np.array(rows[name], dtype=float)
    m = float(np.nanmean(v))
    bar = "#" * int(round(m / 5))
    print(f"  {name:<8} {m:7.1f}  {np.nanmin(v):6.1f}  {np.nanmax(v):6.1f}   {bar}")

print("\nexpectation: good highest; fast/late/gap clearly lower; "
      "noisy near good (it must not punish a bad room); slow lowest; "
      "lead near good (capture latency is not the speaker's fault).")
ok = True
if np.nanmean(rows["good"]) < 85:
    print("\nFAIL: re-reading the original must score near 100")
    ok = False
for name in ("slow", "fast", "late", "gap"):
    if np.nanmean(rows[name]) >= np.nanmean(rows["good"]) - 8:
        print(f"\nFAIL: {name} is not measurably worse than a correct reading")
        ok = False
if np.nanmean(rows["noisy"]) < np.nanmean(rows["good"]) - 20:
    print("\nFAIL: a noisy recording collapsed the score — the metric is "
          "scoring the room, not the speech")
    ok = False
if np.nanmean(rows["lead"]) < np.nanmean(rows["good"]) - 12:
    print("\nFAIL: 400ms of capture latency was charged to the speaker. The "
          "onset correction must absorb it; if this fails, the browser is "
          "being asked to report a start time it cannot know.")
    ok = False
print("\n" + ("PASS" if ok else "FAIL"))
sys.exit(0 if ok else 1)