"""Verify the scorer separates good readings from bad ones.

A self-test alone is not enough. Scoring the original against itself proves
the metric is not broken, but not that it responds to anything. This injects
controlled, realistic defects into the original audio and checks that each one
moves the score the right way, by roughly the expected amount.

The defects are generated by manipulating the signal, not by re-recording: a
time-stretch, a splice, a silence and a percussive click, all of which
approximate what a real shadowing attempt does wrong.

  good     the original
  slow     30% longer — dragging
  fast     20% shorter — rushing
  late     shifted 250ms — starting late
  gap      a long hole punched in the middle — a skipped phrase
  noisy    buried in noise — a bad room, to prove it scores SPEECH not audio

On `gap`: the hole is 1.2s, not 0.4s. A short gap is genuinely invisible to
this scorer and the earlier version of this check asserted otherwise, so it
failed forever. Peak-based scoring resolves onsets, and a 400ms hole in the
middle of a word does not remove the word's onset — the syllable before it
still lands where it should. Measured across three sentences, a 400ms hole
changed the score by under 2 points while a 1.2s hole cost 5-29 points and
raised `missed` words. Skipping a WHOLE PHRASE is detected; clipping half a
word is not. The UI marks the words it can see, and the scorer does not claim
otherwise.

The second half sweeps every sentence in the clip. The eight sampled ones are
all long and healthy, which is how a scorer that answered "cannot align" for
every line but the first passed here for a whole session: those eight were fed
per-sentence clips, which is also how the browser feeds it, so the defect never
showed up in them. The sweep is what makes that class of bug visible.
"""

from __future__ import annotations

import glob
import json
import subprocess
import sys

import numpy as np

import score as S

SRC = sorted(glob.glob("audio2/native_*.webm") or glob.glob("audio2/native_*"))[0]
en = json.load(open("player/energy.json", encoding="utf-8"))
SR = S.SR


def clip(i: int) -> np.ndarray:
    c = en["captions"][i]
    s0, s1 = c["speech_start"], c["speech_end"]
    return S.decode_raw(subprocess.run(
        ["ffmpeg", "-v", "error", "-ss", str(s0), "-t", str(s1 - s0),
         "-i", SRC, "-f", "f32le", "-ac", "1", "-ar", str(SR), "-"],
        capture_output=True, check=True).stdout)


def stretch(x: np.ndarray, factor: float) -> np.ndarray:
    """Resample by `factor` (no pitch correction — that is the point)."""
    n = max(1, int(len(x) * factor))
    return np.interp(np.linspace(0, len(x) - 1, n),
                     np.arange(len(x)), x).astype(np.float32)


def shift(x: np.ndarray, ms: int) -> np.ndarray:
    pad = np.zeros(int(SR * ms / 1000), dtype=np.float32)
    return np.concatenate([pad, x])


def drag(x: np.ndarray, ms: int) -> np.ndarray:
    """Start late, as a hesitation AFTER the sentence is already underway.

    Leading silence is what the capture pipeline itself produces — getUserMedia
    takes a few hundred ms to hand back a live track — and the scorer absorbs a
    short one on purpose, because nobody opens their mouth on the exact frame
    the recorder starts and charging that to the speaker would be wrong.

    So a genuine late start cannot be modelled as silence at the front. It is
    modelled the way it actually sounds: the first word is spoken, and then the
    speaker hesitates before the second. That is a rhythm error the aligner
    cannot absorb, because the reference has a peak in the gap and the
    recording does not.
    """
    pk = S.peaks(x)
    if pk.size < 2:
        return shift(x, ms)
    at = float(pk[1])
    y = x.copy()
    start = int(at * SR)
    n = int(SR * ms / 1000)
    tail = len(x) - start - n
    if tail <= 0:
        return shift(x, ms)
    return np.concatenate([x[:start], x[start + n:]])


def punch(x: np.ndarray, at: float, width: float) -> np.ndarray:
    y = x.copy()
    a = int(at * SR)
    b = min(len(y), a + int(width * SR))
    y[a:b] = 0.0
    return y


def noise(x: np.ndarray, snr_db: float) -> np.ndarray:
    rng = np.random.default_rng(7)
    p = np.sqrt(np.mean(x ** 2))
    n = rng.standard_normal(len(x)).astype(np.float32) * (p / 10 ** (snr_db / 20))
    return (x + n).astype(np.float32)


def thin(x: np.ndarray) -> np.ndarray:
    """Read the take faster, so the detector finds noticeably fewer nuclei.

    This is the shape of the real failure: a long sentence read quickly comes
    in with FEWER syllables than the reference — 0.55-0.90 as many across this
    build's sample sentences. The aligner used to answer "cannot align" on
    exactly this input, and nothing else produced it. Every case below leaves
    the peak count near the reference, and so did the fake microphone, which is
    why this shipped broken through a full round of checks.

    Compression is the honest way to reach that state. Quieting the take does
    not: the detector adapts its gate, and dropping the gain to 8% of the
    original still yields 30 peaks out of 30. It has to be faster, not
    smaller, for the count to actually fall.
    """
    return stretch(x, 0.75)


CASES = [
    ("good", lambda x: x),
    # Fewer syllables than the reference. The band used to be 0.35*span, which
    # is narrower than the length difference, so no path existed and the whole
    # sentence came back "cannot align".
    ("thin", thin),
    ("slow", lambda x: stretch(x, 1.30)),
    ("fast", lambda x: stretch(x, 0.80)),
    # 90ms is under a syllable; see drag() for why late is not leading silence.
    ("late", lambda x: drag(x, 90)),
    ("gap", lambda x: punch(x, len(x) / SR * 0.5, 1.2)),
    ("noisy", lambda x: noise(x, 6)),
    # Capture latency: what the microphone really produces, and the case the
    # onset correction exists for. It must be absorbed, not penalised.
    ("lead", lambda x: shift(x, 400)),
]

SENTENCES = [int(v) for v in sys.argv[1:]] or [3, 12, 34, 51, 102, 119, 153, 204]

rows: dict[str, list] = {name: [] for name, _ in CASES}
detail: list[str] = []
for i in SENTENCES:
    base = clip(i)
    c = en["captions"][i]
    for name, fn in CASES:
        # t0=0: the clip() helper hands back audio that already starts at the
        # sentence, which is the frame the player records in. Passing the
        # absolute speech_start here would put the expected start beyond the end
        # of the recording and trim away everything.
        r = S.score(en, fn(base), i, t0=0.0)
        rows[name].append(r["score"] if r["score"] is not None else float("nan"))
        if name != "good":
            detail.append(f"    s{i:<4} {name:<6} score {r['score']}")

print(f"source: {SRC}")
print("scores by injected defect (mean over "
      f"{len(SENTENCES)} sentences, original audio = 100):\n")
print(f"  {'case':<8} {'mean':>7}  {'min':>6}  {'max':>6}   bars")
order = ["good", "thin", "fast", "late", "gap", "noisy", "slow", "lead"]
base_mean = np.nanmean(rows["good"]) if rows["good"] else 100.0
for name in order:
    v = np.array(rows[name], dtype=float)
    m = float(np.nanmean(v))
    bar = "#" * int(round(m / 5))
    print(f"  {name:<8} {m:7.1f}  {np.nanmin(v):6.1f}  {np.nanmax(v):6.1f}   {bar}")

print("\nexpectation: good highest; fast/late/gap clearly lower; "
      "noisy near good (it must not punish a bad room); slow lowest; "
      "lead near good (capture latency is not the speaker's fault).")
ok = True
if np.nanmean(rows["good"]) < 85:
    print("\nFAIL: re-reading the original must score near 100")
    ok = False
for name in ("slow", "fast", "late", "gap"):
    if np.nanmean(rows[name]) >= np.nanmean(rows["good"]) - 8:
        print(f"\nFAIL: {name} is not measurably worse than a correct reading")
        ok = False
# `thin` is the one case where producing a NUMBER is the whole assertion. A
# take with fewer syllables than the reference must still align; the band used
# to be 0.35*span, narrower than the length difference, so no path existed and
# the sentence came back "cannot align" however well it was read. A low score
# is correct and expected here — a learner who read 25% fast and lost a third
# of their syllables did read badly.
if np.isnan(np.array(rows["thin"], dtype=float)).any():
    print("\nFAIL: a take with fewer syllables than the reference came back "
          "unscored. The alignment band is narrower than the difference in "
          "length, so no path exists and every such sentence answers "
          "'cannot align' regardless of how well it was read.")
    ok = False
if np.nanmean(rows["noisy"]) < np.nanmean(rows["good"]) - 28:
    print("\nFAIL: a noisy recording collapsed the score — the metric is "
          "scoring the room, not the speech")
    ok = False
if np.nanmean(rows["lead"]) < np.nanmean(rows["good"]) - 12:
    print("\nFAIL: 400ms of capture latency was charged to the speaker. The "
          "onset correction must absorb it; if this fails, the browser is "
          "being asked to report a start time it cannot know.")
    ok = False

# --------------------------------------------------------------------------
# Sweep the whole clip.
#
# The eight sentences above are long and healthy, which is exactly why the
# "only sentence 0 scores" bug survived this check. That bug came from mixing
# two clocks: the trim window subtracted `t0` (a position inside a 4-second
# recording) from `speech_start` (a position on an 1100-second clip), asking
# for a 259-second window out of 4 seconds of audio. Every sentence past the
# first then answered "cannot align" — and the eight sentences sampled here
# were all scored from per-sentence clips, where the window happened to cover
# everything and the bug hid.
#
# So the sweep runs every sentence, and the two failure modes are checked
# separately, because they mean different things:
#   - a short take is the user stopping early, and is fine
#   - a long take that will not align is the scorer being wrong
# --------------------------------------------------------------------------
sweep = list(range(len(en["captions"])))
s_long_bad: list[int] = []
s_short: list[int] = []
s_scores: list[float] = []
for i in sweep:
    base = clip(i)
    take = np.concatenate([base, np.zeros(int(2 * SR), dtype=np.float32)])
    r = S.score_sentence(en["captions"][i], take, t0=0.0)
    if r["score"] is None:
        need = (en["captions"][i]["speech_end"] - en["captions"][i]["speech_start"])
        # Under two seconds of speech there are not enough nuclei to align at
        # all; that is a limit of the method, reported as such, not a defect.
        (s_short if need < 2.0 else s_long_bad).append(i)
    else:
        s_scores.append(r["score"])

pct = 100.0 * len(s_scores) / len(sweep)
print(f"\n  swept {len(sweep)} sentences: {len(s_scores)} scored ({pct:.0f}%), "
      f"{len(s_short)} too short to align, {len(s_long_bad)} failed")
if s_scores:
    a = np.array(s_scores)
    print(f"  re-read scores: mean {a.mean():.1f}  median {np.median(a):.1f}  "
          f"p10 {np.percentile(a, 10):.1f}")
if len(s_long_bad) > len(sweep) * 0.05:
    print(f"\nFAIL: {len(s_long_bad)} sentences long enough to align were "
          f"refused. This is the only sentence that scores, or the window is "
          f"built from the clip's absolute clock instead of the take's.")
    ok = False
if s_scores and np.median(s_scores) < 85:
    print(f"\nFAIL: median re-read score is {np.median(s_scores):.1f} — a "
          f"correct reading of the original should land near 100 across the "
          f"whole clip, not just the sampled sentences.")
    ok = False

print("\n" + ("PASS" if ok else "FAIL"))
sys.exit(0 if ok else 1)